### ISSUE TITLE
Keine Geburtstage gefunden

### ISSUE THREAD

**Issue by BenAhrdt** [klein0r/ioBroker.birthdays#109]
### The problem

Es erscheint der Fehler "no birthdays found" und diese Warnungen dahinter:

![image](https://user-images.githubusercontent.com/92173565/191422539-cee331ab-464e-49c2-a411-a9d7187b5fdb.png)

Man muss den Adapter einmal neu starten, dann läuft er wieder.

### Version of nodejs

16.15.1

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

2.1.0

### Operating system running ioBroker

docker

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

Leider kann ich keinen log im debug mode hinzufügen, da nach dem Neustart des adapters immer wieder alles läuft (Oft auch für 1-2 Monate)
Hatte den "Fehler" nun ca. 3 mal.

**Comment by klein0r** [comment]
Das ist komisch (und auch etwas unlogisch). Immerhin ist das ein Schedule-Adapter. Das heißt, der läuft eh nicht durch.
Ein "Neustart" bringt somit nichts. Der nächste geplante Start nach Schedule wäre genau das gleiche wie ein Neustart.

Was war denn um 0 Uhr? Haben da auch andere Adapter Probleme gemacht zu der Zeit? Wenn die DB geschlossen wurde, dann müssten ja auch alle anderen Instanzen da drüber stolpern in der Zeit.
