### ISSUE TITLE
Wo sind eigentlich die manuell eingetragenen Geburtstage gespeichert

### ISSUE THREAD

**Issue by Bavarianspirit** [klein0r/ioBroker.birthdays#118]
### The problem

Ich würde gerne die Geburtstage per VIS editieren. Und zwar diese, welche über den Reiter Geburtstage im Adapter eingetragen werden.
Gibt es hier eine Möglichkeit?

### Version of nodejs

xxx

### Version of ioBroker js-controller

xxx

### Version of Adapter

xxx

### Operating system running ioBroker

xxx

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
> Gibt es hier eine Möglichkeit?

Nein - außer total umständlich, indem Du das Instanz-Objekt ``system.adapter.birthdays.0`` bearbeitest (native).
Aber wann ändert sich denn ein Geburtstag? Und wie soll der Editier-Dialog aussehen?
Verdammt viel Arbeit für sehr wenig Nutzen aus meiner Sicht.
