### ISSUE TITLE
already been added Bug report

### ISSUE THREAD

**Issue by DrGalvany** [klein0r/ioBroker.birthdays#147]
### The problem

Hallo, 
seit Version 2.2.2 kommt immer diese Warnung im log, bei zwei Personen.
Wo habe ich einen Fehler?
Habe den Kalender geprüft, die Personen sind wie die anderen einmal vorhanden.

Danke Micha

> <html>
<body>

birthdays.0 | 2023-07-01 00:00:05.315 | warn | [addBirthday] birthday with name "Max Musterman" has already been added (30.10.2023) - skipping
-- | -- | -- | --

</body>
</html>

### Version of nodejs

2.2.2

### Version of ioBroker js-controller

19.16.1

### Version of Adapter

6.3.5

### Operating system running ioBroker

Linux Debian 12

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Ja und jetzt? 😄 Soll ich den Kalender korrigieren? Da ist wohl ein Termin doppelt gepflegt
