### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by ahennies-22** [klein0r/ioBroker.birthdays#71]
### The problem

When I start the instance of the adapter, I always get the error message Error in GUI
I have a brand new ioBroker installation and the latest version 0.1.6 is installed. In my old environment I use version 0.0.3 and there are no problems.
No logs in debug mode

### Version of nodejs

V12.22.8

### Version of ioBroker js-controller

v5.1.25

### Version of Adapter

0.1.6

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

3react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140)
    at d (react-dom.production.min.js:144)
    at v (react-dom.production.min.js:146)
    at react-dom.production.min.js:150
    at Ro (react-dom.production.min.js:176)
    at Ui (react-dom.production.min.js:271)
    at Cl (react-dom.production.min.js:250)
    at _l (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
ii @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
uc @ react-dom.production.min.js:130
Io @ react-dom.production.min.js:184
Ui @ react-dom.production.min.js:269
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonym) @ index.js:145
Promise.then (async)
(anonym) @ index.js:141
Promise.then (async)
value @ index.js:139
n @ index.js:75
mc @ react-dom.production.min.js:135
Io @ react-dom.production.min.js:181
Ui @ react-dom.production.min.js:269
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonym) @ JsonConfig.js:115
Promise.then (async)
(anonym) @ JsonConfig.js:113
Promise.then (async)
(anonym) @ JsonConfig.js:110
Promise.then (async)
n @ JsonConfig.js:109
mc @ react-dom.production.min.js:135
Io @ react-dom.production.min.js:181
Ui @ react-dom.production.min.js:269
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
2allpages.js:118 Content script injection failed, reloading

**Comment by klein0r** [comment]
1. "5.1.25" is not the js-controller version, it is the admin version :)
2. This adapter requires (at least) admin "5.1.28" (which is not stable right now)
3. you should update your nodejs version to 14
