### ISSUE TITLE
Geburtstage

### ISSUE THREAD

**Issue by Thorsten2477totti** [klein0r/ioBroker.birthdays#72]
### The problem

Wenn ich einen Namen eingebe und dann das Datum ist alles gut. Gebe ich das Jahr ein bekomme ich um die Speichern Button ein roter Kasten und kann nicht speicher...... Nur beim Jahr

### Version of nodejs

v14.18.2

### Version of ioBroker js-controller

3.3.21

### Version of Adapter

v0.1.6

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [X] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

<html>
<body>

birthdays.0 | 2021-12-21 15:22:11.707 | warn | Clear yet terminated timer 2
-- | -- | -- | --
birthdays.0 | 2021-12-21 15:21:18.893 | warn | Clear yet terminated timer 2
birthdays.0 | 2021-12-21 15:18:21.645 | warn | Clear yet terminated timer 2

</body>
</html>

**Comment by klein0r** [comment]
Das ist ein Bug im Admin-Adapter in Kombination mit Tabellen. So richtig konnte ich das auch noch nicht nachvollziehen.

**Comment by klein0r** [comment]
Check 0.1.7

**Comment by Thorsten2477totti** [comment]
Danke schön.

**Comment by Chaot1** [comment]
Der Fehler taucht bei mir auch mit der Version 0.1.7 auf.

Um es weiter einzugrenzen:
Wenn ich direkt die Jahreszahl eingebe kommt der Fehler.
Wenn ich aber auf die kleinen Up- Down Button klicke springt er auf 1900 und lässt sich dann hochzählen. Dabei bleibt das Speichern aktiv.
Sobald man aber den Cursor in das Zahlenfeld setzt ist der Button wieder aus mit dem roten Rand.

**Comment by klein0r** [comment]
> Der Fehler taucht bei mir auch mit der Version 0.1.7 auf.

Ab 0.1.7 wird die Jahreszahl doch direkt mit einem Standard-Wert gefüllt? Klingt so, als solltest Du nochmal Upload auf dem Adapter ausführen :)

**Comment by Chaot1** [comment]
Trotz erneutem Upload der gleiche Effekt.
Sobald ich ein Geburtsjahr verändern möchte und nicht die beiden Buttons benutze sondern direkt in das Feld schreibe kommt der rote Rand und lässt sich nicht speichern.

Ich habe den auch mal als zweite Instanz installiert und auch dort genau den gleichen Fehler.
