### ISSUE TITLE
Error calculating next birthday

### ISSUE THREAD

**Issue by phoenix-pnp** [klein0r/ioBroker.birthdays#74]
### The problem

As visible from the following screenshot, the next birthday object is miscalculated. Four other birthdays are before that birthday and their dates have been recognized correctly by the adapter.
One example is in the following screenshot:
![image](https://user-images.githubusercontent.com/18349726/147930490-3debac98-ccce-4c0a-bede-afa72ba4a555.png)

### Version of nodejs

v14.18.2

### Version of ioBroker js-controller

3.3.22

### Version of Adapter

0.1.7

### Operating system running ioBroker

Raspberry OS "Bullseye"

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

I can provide you with a full log via mail or thru other private channels, but due to birthdays being personal data I cannot post them here

**Comment by klein0r** [comment]
Please provide the log files

**Comment by phoenix-pnp** [comment]
Was reproducible this morning, now with 0.1.8 it is gone.
I guess it the error was created by the adapter having to calculate NaN dates.
I can confirm both bugs look good now.
Thanks for your fast help!
Danke und viele Grüße
Ben

**Comment by klein0r** [comment]
Thanks for your issue report - there is always an unexpected edge case ... 😄
