### ISSUE TITLE
"save" and "save and close" button greyed out if year of birth are typed in manually

### ISSUE THREAD

**Issue by martin2704-Ger** [klein0r/ioBroker.birthdays#78]
### The problem

The "save" and "save and close" buttons become unavailable if year-of-birth is typed in manually not using the up/down arrows to change the value in the Birthdays tab. This does not occur on other input fields. If the up/down buttons are used to change the value of year-of-birth field the save and save and close option stays available

### Version of nodejs

14.19.0

### Version of ioBroker js-controller

3.3.22

### Version of Adapter

1.0.0

### Operating system running ioBroker

Debian 11 VM under Proxmox

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

[birthdayAdapterLog.txt](https://github.com/klein0r/ioBroker.birthdays/files/8098538/birthdayAdapterLog.txt)
![Bildschirmfoto 2022-02-18 um 17 03 10 PM](https://user-images.githubusercontent.com/69475856/154718128-0767ca14-361a-49a6-a1b4-edb4f8e3dc37.png)

**Comment by klein0r** [comment]
Yes, this is an (already reported) Admin 5 bug: https://github.com/ioBroker/ioBroker.admin/issues/1263
