### ISSUE TITLE
birthdays.0 already running

### ISSUE THREAD

**Issue by mrjeschke** [klein0r/ioBroker.birthdays#79]
### The problem

Adapter wird seit Version 1.1.0 nicht mehr beendet.
Beim nächsten Start kommt dann der Fehler.

2022-02-26 11:14:04.769 | error | instance system.adapter.birthdays.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
-- | -- | --
birthdays.0 | 2022-02-26 11:14:04.239 | warn | Terminated (ADAPTER_ALREADY_RUNNING): Without reason
birthdays.0 | 2022-02-26 11:14:04.238 | error | birthdays.0 already running

### Version of nodejs

14.19.0

### Version of ioBroker js-controller

4.0.15

### Version of Adapter

1.1.1

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Fixed in 1.1.3
