### ISSUE TITLE
Save button deactivated

### ISSUE THREAD

**Issue by chibbez** [klein0r/ioBroker.birthdays#81]
### The problem

While creation new manual entries, when I use the arrow up/down button, everything is good.
When I start typing especially the year manually figure by figure, then the field checker says value too short and deactivates the save buttons. 
After completing the year with a valid year, the save button stays deactivated.

### Version of nodejs

14.19.2

### Version of ioBroker js-controller

4.0.21

### Version of Adapter

1.2.1

### Operating system running ioBroker

Linux / RPI

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

I am using last MacOS with Safari ... 

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/37547250/168475469-abe11ed2-f849-4e2e-98af-e43283c5d6e9.png">

Also in Chrome:
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/37547250/168475533-f8f714a8-d3c1-40ec-9dd7-646ab8ab01d9.png">

**Comment by klein0r** [comment]
It’s an admin bug. See https://github.com/ioBroker/ioBroker.admin/issues/1263
